name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  namespace: 'janortop5'
  repository: 'laravel'
  image_tag: 'v1'
  registry: 'docker.io'
  dockerfile: 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest # ${{matrix.os}}
#     strategy:
#       matrix:
#         os: [ubuntu-latest, windows-latest, macOS-latest]
        
    steps:
    - uses: actions/checkout@v3    
    
    - name: Set up Image build
      run: |
        cd laravel-app/
        cp ${{ secrets.ENV_FILE }} .env.example
      
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: $namespace/$repository
        tags: $image_tag, latest
        registry: $registry
        dockerfile: $dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
