name: Build Test Deploy Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  namespace: 'janortop5'
  repository: 'laravel'
  image_tag: 'v1'
  registry: 'docker.io'
#   dockerfile: 'laravel-app/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest # ${{matrix.os}}
#     strategy:
#       matrix:
#         os: [ubuntu-latest, windows-latest, macOS-latest]
        
    steps:
    - uses: actions/checkout@v3    
    
    - name: Set up Image build
      run: |
        cd laravel-app/
        echo ${{ secrets.ENV_FILE }} > .env.example

    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: $namespace/$repository
        tags: $image_tag, latest
        registry: $registry
        dockerfile: laravel-app/Dockerfile
        directory: laravel-app/
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
  laravel_test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3 
      
      - name: Copy env file
        run: |
          cd laravel-app/
          echo ${{ secrets.TEST_ENV_FILE }} > .env.example
          cp .env.example ../.env          
      
      - name: Test Laravel App
        run: |
          cd laravel-app/
          docker compose up -d
          docker compose exec laravel php artisan migrate --seed --env=development
          docker compose exec laravel php artisan test --env=development
        env:
          .env: ${{ secrets.TEST_ENV_FILE }}
          
