name: Build Test Deploy Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  namespace: 'janortop5'
  repository: 'laravel'
  image_tag: 'v1'
  registry: 'docker.io'
  DB_DATABASE: ${{ secrets.DB_DATABASE }}}}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}}}
  server_user: 'root'
  server_ip: '64.226.66.96'
  branch: 'new-ci-workflow'

jobs:
  build:
    runs-on: ubuntu-latest # ${{matrix.os}}
#     strategy:
#       matrix:
#         os: [ubuntu-latest, windows-latest, macOS-latest]
        
    steps:
    - uses: actions/checkout@v3    
    
    - name: Set up Image build
      run: |
        cd laravel-app/
        echo ${{ secrets.ENV_FILE }} > .env.example

    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: $namespace/$repository
        tags: $image_tag, latest
        registry: $registry
        dockerfile: laravel-app/Dockerfile
        directory: laravel-app/
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
  laravel_test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3 
      
      - name: Test Laravel
        run: |
          cd laravel-app
          echo ${{ secrets.SSH_KEY }} > testing.pem
  
  # laravel_test:
  #   runs-on: ubuntu-latest
    
  #   steps:
  #     - uses: actions/checkout@v3 
      
  #     - name: Copy env file
  #       run: |
  #         cd laravel-app
  #         echo ${{ secrets.TEST_ENV_FILE }} > .env.example
  #         chmod +x laravel_test.sh
  #         ./laravel_test.sh
    
  # laravel_test:
  #   runs-on: ubuntu-latest
    
  #   steps:
  #     - uses: actions/checkout@v3 
      
  #     - name: Copy env file
  #       run: |
  #         cd laravel-app/
  #         echo ${{ secrets.TEST_ENV_FILE }} > .env.example   
      
  #     - name: Test Laravel App
  #       run: |
  #         cd laravel-app/
  #         # export DB_PASSWORD=${{ secrets.DB_PASSWORD }}}}
  #         # export DB_DATABASE=${{ secrets.DB_DATABASE }}}}
  #         docker compose up -d
  #         sleep 160
  #         docker exec laravel php artisan migrate --seed --env=development
  #         docker exec laravel php artisan test --env=development
